# Generated by Django 4.2.1 on 2023-05-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
